[package]
name = "blochain1_project_midterm_final"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.0"
solana-program = "1.14.11"
solana-sdk = "1.8.2"
solana-frozen-abi = "1.18.14"

[dev-dependencies]
solana-program-test = "1.14.11"
